2d:
	td3-learn.py --env gym_copter:Lander-v0 --target 300 --checkpoint

3d:
	td3-learn.py --env gym_copter:Lander3D-v0 --target 300 --checkpoint

best:
	ls -c1 models | head

clean:
	rm -rf models/ runs/ *.mp4
