#
# Makefile for convenience
#
# Copyright (C) 2020 Simon D. Levy
#
# MIT License
#

neat0:
	neat-evolve.py --env gym_copter:Lander3D-v0 --checkpoint

neat1:
	neat-evolve.py --env gym_copter:Lander3D-v1 --checkpoint

clean:
	rm -rf models/ visuals/
